"""initial tables

Revision ID: 25eb6338277f
Revises: 
Create Date: 2026-03-29 12:34:07.908388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25eb6338277f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_events_camera_id'), 'camera_events', ['camera_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('hmm_feedback',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('from_cam', sa.String(length=50), nullable=False),
    sa.Column('to_cam', sa.String(length=50), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('query_type', sa.String(length=10), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('viterbi_path', sa.JSON(), nullable=True),
    sa.Column('total_images', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_sessions_session_id'), 'search_sessions', ['session_id'], unique=True)
    op.create_table('correction_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('original_image_path', sa.Text(), nullable=True),
    sa.Column('corrected_image_path', sa.Text(), nullable=False),
    sa.Column('corrected_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('original_weight', sa.Float(), nullable=True),
    sa.Column('corrected_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['search_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_history_session_id'), 'correction_history', ['session_id'], unique=False)
    op.create_table('search_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['search_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_results_session_id'), 'search_results', ['session_id'], unique=False)
    op.create_table('vehicle_sightings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['search_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_sightings_session_id'), 'vehicle_sightings', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_sightings_session_id'), table_name='vehicle_sightings')
    op.drop_table('vehicle_sightings')
    op.drop_index(op.f('ix_search_results_session_id'), table_name='search_results')
    op.drop_table('search_results')
    op.drop_index(op.f('ix_correction_history_session_id'), table_name='correction_history')
    op.drop_table('correction_history')
    op.drop_index(op.f('ix_search_sessions_session_id'), table_name='search_sessions')
    op.drop_table('search_sessions')
    op.drop_table('hmm_feedback')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_camera_events_camera_id'), table_name='camera_events')
    op.drop_table('camera_events')
    # ### end Alembic commands ###
